# Generated by Django 4.2.4 on 2023-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options_remove_article_scopes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag2',
            field=models.ManyToManyField(related_name='article', through='articles.Scope', to='articles.tag'),
        ),
    ]
