# Generated by Django 4.2.4 on 2023-09-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_tag_article_tag2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag2',
            new_name='tag',
        ),
    ]
