# Generated by Django 4.2.5 on 2023-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_sensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
